### ISSUE TITLE
regular parse rules get ignored if custom ones exist

### ISSUE THREAD

**Issue by Yokozuna59** [langium/langium#1069] opened 2023-06-01 16:52 UTC
Langium version: 1.2.0
Package name: mermaid-parser

## Steps To Reproduce

1. Created custom `TokenBuilder`.
2. Set custom pattern function.
3. add the custom `TokenBuilder` to language module.
4. parse the code

Link to code example:

- custom token builder: https://github.com/Yokozuna59/mermaid-lint/blob/master/packages/mermaid-parser/src/language/mermaid-token-builder.ts#L11-L36
- custom pattern function: https://github.com/Yokozuna59/mermaid-lint/blob/master/packages/mermaid-parser/src/language/matchers/title.ts#L10-L22
- regular parse rule in grammar: https://github.com/Yokozuna59/mermaid-lint/blob/master/packages/mermaid-parser/src/language/grammars/pie.langium#L11-L13
- custom parse rule in grammar: https://github.com/Yokozuna59/mermaid-lint/blob/master/packages/mermaid-parser/src/language/grammars/pie.langium#L7

## The current behavior

It's parses until the custom one, and build the AST without parsing the `Section` regular rule. Which results in throwing `NotAllInputParsedException` exception.

![image](https://github.com/langium/langium/assets/87622592/de46f99c-b173-4537-90f9-a6218ae9c5b7)

## The expected behavior

No error.

**Comment by Yokozuna59** [comment] 2023-06-01 17:47
> ...Can you try whether the issue still exists if you change the `NEWLINE+` to `NEWLINE*`?

It works, but it's breaks another case, the following code shouldn't be valid:

![image](https://github.com/langium/langium/assets/87622592/3b1dac75-cbe0-46a4-96b2-0c0f1b6f80be)

**Comment by Yokozuna59** [comment] 2023-06-01 17:55
I'm able to make it work by changing the grammar to be this:

```langium
entry PieChart:
    NEWLINE*
    "pie" (showData?="showData")? NEWLINE*
    TITLE_AND_ACCESSIBILITIES? (NEWLINE* |
    ((NEWLINE+ sections+=Section)+ NEWLINE*)?)
;
```

But it's a bit complex.

**Comment by Yokozuna59** [comment] 2023-06-01 19:18
I don't know what happened but it's working now although I haven't change the grammar. Anyway, another error occurred, if there is more than one NEWLINE after `pie` it's breaks tho I've `NEWLINE*`:

```langium
entry PieChart:
    NEWLINE*
    "pie" (showData?="showData")? NEWLINE*
    TITLE_AND_ACCESSIBILITIES?
    ((NEWLINE+ sections+=Section)+ NEWLINE*)?
;

fragment TITLE_AND_ACCESSIBILITIES:
    (accDescr=ACC_DESCR | accTitle=ACC_TITLE | title=TITLE)+
    NEWLINE*
;
```

![image](https://github.com/langium/langium/assets/87622592/923a5f9a-30df-4799-b0b7-a88d5a565e37)

![image](https://github.com/langium/langium/assets/87622592/8541ecef-9178-4973-bc1e-2cbb9ad207fe)

**Comment by msujew** [comment] 2023-06-01 20:18
I'm unable to reproduce the issue on the [langium playground](https://langium.org/playground?grammar=OYJwhgthYgBACgSwKYHFxRgKC8gdgC4gCeCKAwgBYwEBcWsjsAcgKIDqAMgJJsBUDJgCIADiiGwAFAGdKAewDuAETAEwAfgC8Q2YpVqhASnUsOPfoMYAVblc6sA%2BgEFmS5%2BXKsAyl%2B4Ahbh4bb3VLKUk2Ll5WAGpYaWQAYwJEOTxpGM0vJJS0wzjI81Y%2BYywAbhxs5NS8eiZYABswACNkBqyrACVeVFghWgkANzAGgFdkTWYAVQBZP1ZO8pwAM3BgCHwCWBs7Rxc3Jw9vXwCg7m86pkkwRMSlZGlEkE1D8gclb3JO2AAfWBvElZEAQGhNXg4dvZfrAUiCJpDWPkwoVogIKlgAPR8GHIEAQRB4EbSWB8DFYAi4-GEhqmKJsWiwDEAbQAOngWSAALoYiqURAAE35%2BBxeIJI1g7AAErZvPBDqwGcyWQQObBOTEeTgMRjtgB5JS6hlgQWwACaThmnAc5F1MxmrGYVlgfMFwpAo1BWBdQrwIqp4vNlsVAFpQyzpHxWeyuazpCyvJy%2BOpQ8Hw3xJOoAIQAOkMmu9wopoupsBmU04NgcRWttvtjsVAFIGyzI%2BH44n1C2m2n8wKfX6xTSlNxOqxyDYAGoKxlNgDesfbSYAvt2I73Xb6i-6ab5mKh7FXojW7Q6rI2G0yAHpsjmJnvoreD2Dgj5eL6KgH3R5wDWwbhKCpHxLcEEQ-W4gThWBf3-QDKSfUDGVhUEoJ1GCcCA8UvC6HpFSEK8hETIRNXJOCS3-RUmQcMBgwALycYMAC1OVZBQHETYiMJpaY5gWWAQGQAhRhAdJYDwUYIFaEBFUkAAGH4mQARmDABOZiZJUxNDEkFlsyZdTVJiYweSAA&content=A4SwpgUFUC4jAbMACAZgQwM4BMu%2BkA). Since the discussion has changed quite a bit from the original issue, I'll close this issue. If you have further questions, please open a discussion instead.

**Closed by msujew** 2023-06-01 20:18 UTC
Labels: bug

**Comment by Yokozuna59** [comment] 2023-06-01 21:50
Thanks! In case if someone is wondering, I came up with this:

```langium
entry PieChart:
    NEWLINE*
    "pie" (showData?="showData")?
    (NEWLINE* TITLE_AND_ACCESSIBILITIES)?
    (NEWLINE+ sections+=Section)*
    NEWLINE*
;

fragment TITLE_AND_ACCESSIBILITIES:
    (accDescr=ACC_DESCR | accTitle=ACC_TITLE | title=TITLE)+
;
```

Which resolves `chevrotain` logging, cleaner syntax, no `NEWLINE` would be consumed greedily.

**Comment by msujew** [comment] 2023-06-02 10:09
@Yokozuna59 On a unrelated note, I spoke with a colleague today about a very similar issue (i.e. `NEWLINE` at the start of a group). We identified that missing `NEWLINE` tokens will often lead to error recovery issues in the parser. That might not be too interesting for your use case, but if you ever want an interactive editor for the language, I would recommend the following:

1. Move every `NEWLINE+` to the end of statements. Having it at the start makes the parser skip groups such as `(NEWLINE+ sections+=Section)*` in case there are no `NEWLINE` tokens.
2. Override the `Lexer` service to always return a `NEWLINE` token at the end of the token stream. That way you don't need to work with the `EOF` token (which doesn't seem to work, we've also experienced this issue recently).

**Comment by Yokozuna59** [comment] 2023-06-02 15:36
@msujew I don't think any of those solutions are suitable enough for my use case since they break other parts. I'll go with the above solution since it's for the current grammar. I'll rethink it when I get to a dead end while continuing to work on the parser.
