### ISSUE TITLE
Cross reference in separate files with rule name same as type name raises error

### ISSUE THREAD

**Issue by luan-xiaokun** [langium/langium#745] opened 2022-10-31 13:40 UTC
The error `Use the rule type 'X' instead of the typed rule name 'X' for cross references.` is raised when

1. The name of the referenced type and the name of its parse rule are the same,
2. The parse rule of the referenced type and the cross reference are placed in different files.

Using different name or placing them in one file can remove this error.

A minimal example:
```
// file debug.langium
grammar Debug

import './foo'

entry Model:
    (b+=B | a+=A)*;

// A infers A:
//     'A' a=ID;

B infers B:
    'B' b=[A:ID];
```

```
// file foo.langium
A infers A:
    'A' a=ID;

terminal ID: /[_a-zA-Z][\w_]*/;
```

Renaming the rule `A` or moving it into debug.langium both resolve the error.

**Comment by msujew** [comment] 2022-11-11 22:11
For anyone interesting in picking this up: This issue can be addressed by overriding the `Linker` for the grammar language and prioritizing interfaces/types over rules when resolving cross references to `AbstractType`.

**Comment by luan-xiaokun** [comment] 2022-11-12 07:28
@msujew If I understand it correctly, the scope provider of langium grammar seems to have already prioritized interfaces and types over rules. So the issue here seems to be the type/interface we want to reference (`A` in the example) not being included in the scope.

https://github.com/langium/langium/blob/824f098b1c924e039aa2884ff82d6544ab4b8ee5/packages/langium/src/grammar/references/grammar-scope.ts#L30-L46

Indeed, in this minimal example, I found no type/interface named `A` in the provided scope, but there is a rule named `A`. (I used the console to print all elements in the scope, something like `scopeProvider.getScope(refInfo).getAllElements().toArray().map(...)`, please let me know if there is a better way to debug this).

If we omit the `infers A`, just write `A: 'A' a=ID`, then the error disappears, but in this case, there is still no interface named `A` in the scope. This error is not raised because now the `type.ref.returnType || type.ref.inferredType` is false, so it passes the validation check. If we remove this condition, then the same error is raised again. This means that when we omit the `infers A` to suppress the error, the cross reference is not correctly resolved (but the generated extension works well).

https://github.com/langium/langium/blob/824f098b1c924e039aa2884ff82d6544ab4b8ee5/packages/langium/src/grammar/langium-grammar-validator.ts#L698-L706

Renaming the rule does not help now, but I'm sure that when I posted this issue renaming was a workaround (on Ubuntu platform). Maybe it's because I'm using Windows platform now?

**Comment by msujew** [comment] 2022-11-12 13:23
@luan-xiaokun Can you see whether https://github.com/langium/langium/pull/763 resolves your issue? I'm actually having trouble reproducing this now. Although I was able to yesterday...

**Comment by luan-xiaokun** [comment] 2022-11-13 04:58
@msujew This fixes the issue. Alghtough I didn't have time to see if there is actually an interface `A` in the scope, it works pretty well.

**Comment by luan-xiaokun** [comment] 2022-11-13 12:00
After a closer look at #763, the `exportNode` method of `LangiumGrammarScopeComputation` can now correctly add interfaces from other documents into the precomputed scope, so when linker try to get a candidate from the scope, the referenced interface can be found, thus resolve this issue.

Although #763 aims to fix #746 at first, it turns out that both issues have similar causes. It would be great if we can add a test for these two issues (I'm not familiar with testing, not sure if it is possible to write a test case involving several documents).

**Comment by spoenemann** [comment] 2022-11-14 09:15
> It would be great if we can add a test for these two issues

See #768

**Comment by msujew** [comment] 2022-12-07 15:16
Closed due to https://github.com/langium/langium/pull/768

**Closed by msujew** 2022-12-07 15:16 UTC
Labels: bug, grammar, linking
