### ISSUE TITLE
Extract common CLI functionality

### ISSUE THREAD

**Issue by pluralia** [langium/langium#174] opened 2021-07-13 13:27 UTC
CLIs in examples perform the same operations:

- check the file name for the extension correctness
- check the file existence
- read and parse content
- check validation errors
- ...

It's nice to extract CLI common functionality in a separate file or package to reuse it. [Here](https://github.com/langium/langium/pull/160#pullrequestreview-703498821) is a discussion.

**Comment by spoenemann** [comment] 2022-12-14 14:56
Duplicate of #239

**Closed by spoenemann** 2022-12-14 14:56 UTC
Labels: cli
