### ISSUE TITLE
`checkGrammarTypeInfer` validation ignores declared types in other .langium files

### ISSUE THREAD

**Issue by pluralia** [langium/langium#728] opened 2022-10-21 15:12 UTC
Definition of a rule `X` and a type `XType` in different files, gives you a validation error `The type 'XType' is not explicitly declared and must be inferred.`
```
interface XType {
    a: string
}

X returns XType:
    a=ID;
```

**Comment by dhuebner** [comment] 2022-11-04 13:50
@pluralia 
I can't  reproduce this issue using the example you provided.
Could you add a real world example that produces the error mentioned above?

**Comment by pluralia** [comment] 2022-11-04 14:11
@dhuebner, I also can't reproduce this issue. I close it.

**Comment by spoenemann** [comment] 2022-11-07 13:04
I can reproduce it by removing the `import` statement.

The error message is misleading. Instead, there should be an error on the return type of `X` because it cannot be resolved.

We should really consider filtering the global scope to include only imported grammars as proposed in https://github.com/langium/langium/issues/746#issuecomment-1303673167.

**Comment by spoenemann** [comment] 2022-11-14 08:23
I disabled the error in #763 with an additional check in the validator:

https://github.com/langium/langium/pull/763/files#diff-3321518d3ed64fdf6ef10fd76c0c81fd6b44242981303125b983f429b36caa1a

But this is only a workaround. I think the analysis made by the validator should filter out unresolved references earlier.

**Comment by dhuebner** [comment] 2022-12-09 11:19
@spoenemann 
The  unresolved return type check you added works as expected and there is no other much better place where to put it.  
So I would propose to close this issue. We can create a new one if the problem described here occurs also after the type system refactoring.

**Closed** 2022-12-12 07:46 UTC
Labels: bug, validation, types
