### ISSUE TITLE
The Monarch generator doesn't add an escape symbol before /

### ISSUE THREAD

**Issue by pluralia** [langium/langium#991] opened 2023-03-15 15:16 UTC
`generateMonarch` doesn't add an escape symbol before `/` what leads to an error.

Langium version: 1.1.0
Package name: langium-cli

## Steps To Reproduce

Create a grammar that uses `/` symbol: [the arithmetic example](https://github.com/langium/langium/blob/main/examples/arithmetics/syntaxes/arithmetics.monarch.ts#LL9C39-L9C39)

## The current behavior
No escape symbol before the `/`: `symbols:  /\(|\)|\*|\+|,|-|/|:|;/`

## The expected behavior
The escape symbol is in its place: `symbols:  /\(|\)|\*|\+|,|-|\/|:|;/`

**Comment by montymxb** [comment] 2023-03-16 07:46
This is a duplicate of #740 , could you add details of this case there as well, and we can close this one out?

**Closed** 2023-03-16 10:11 UTC
Labels: bug, good first issue, monarch
